//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum_xamarinApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int IdLike { get; set; }
        public int IdUtilisateur { get; set; }
        public Nullable<int> IdPublication { get; set; }
        public Nullable<int> IdForum { get; set; }
        public Nullable<int> IdMessage { get; set; }
        public Nullable<int> IdPublicite { get; set; }
        public Nullable<int> IdCommentaire { get; set; }
    
        public virtual Commentaire Commentaire { get; set; }
        public virtual Forum Forum { get; set; }
        public virtual Message Message { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual Publicite Publicite { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
